---
apiVersion: v1
kind: Service
metadata:
  name: webapi-lb
spec:
  selector:
    app: webapi_backend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapi_backend
    spec:
      containers:
      - name: webapi-container
        image: dotnetcoreacr.azurecr.io/dotnetwebapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr